name: Lint DBT Project (SQLFluff)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'models/**.sql'
      - 'seeds/**.csv'
      - 'macros/**.sql'
      - 'dbt_project.yml'

jobs:
  sqlfluff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt and SQLFluff dependencies
        run: |
          python -m pip install --upgrade pip
          # Only install necessary components for linting
          pip install dbt-core dbt-postgres sqlfluff sqlfluff-templater-dbt

      # details on linter rules: https://docs.sqlfluff.com/en/stable/rules.html
      - name: Lint SQL with SQLFluff
        run: sqlfluff lint models/  --dialect postgres --ignore templating